### ISSUE TITLE
Example script / documentation?\

### ISSUE THREAD

**Issue by lancezhang04** [Vorono4ka/3d-converter#5]
Can you please provide a short example script to showcase how we can use this project? It would be super helpful :)

**Comment by danila-schelkov** [comment]
Hello! I have used this module in [this scripts](https://github.com/danila-schelkov/scw-tool). So that repo is an example 😄

**Comment by lancezhang04** [comment]
@danila-schelkov thanks, this is super helpful! I noticed that when converting from .gdb to .obj, the package does not also extract the texture from .gdb or generate a .mtl file. Do you know how one might approach extracting these two files?

**Comment by danila-schelkov** [comment]
There is no way for now, but i think it will be possible later

**Comment by lancezhang04** [comment]
Sounds good, thank you! I'll just use the blender API for the full conversion for now.
